### ISSUE TITLE
api_consts.dart missing 

### ISSUE THREAD

**Issue by RageshAntony** [nitin-787/Ayumi-gpt#7]
### Description

api_consts.dart file is  missing 

so 'unresolved errors' in api_service.dart 

<img width="674" alt="image" src="https://user-images.githubusercontent.com/36100215/228430802-298aff16-f970-4740-839b-ebcc0e0b199d.png">

**Comment by nitin-787** [comment]
@RageshAntony Sure, in order to use this particular API key for ChatGPT, you'll need to generate your own private key. If you're interested in using mine, you can reach out to me on Discord at Ryuk#1867. I am closing this issue as completed

**Comment by RageshAntony** [comment]
@nitin-787 
No. 
It should have the file with a dummy key.

**Comment by nitin-787** [comment]
@RageshAntony 
okay for now here is the dummy file put in inside lib/constants/api_consts.dart

I'll add this dummy file in my next commit or you can do the same while making pull request

`// ignore_for_file: non_constant_identifier_names

String BASE_URL = "https://api.openai.com/v1";
String API_KEY = "Your api key";
`

**Comment by RageshAntony** [comment]
@nitin-787 ok. take your time

**Comment by nitin-787** [comment]
> @nitin-787 ok. take your time

thanks for contribution...
